name: SAP CAP CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Check Node Version
        run: node -v

      - name: Install Dependencies
        run: npm ci

      - name: Install CAP & MBT
        run: |
          npm install -g @sap/cds-dk mbt

      - name: Run Tests
        run: npm test || echo "No tests"

      - name: Build MTA
        run: mbt build -t gen --mtar mta.tar

      - name: Install CF CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" -o cf.tgz
          if [ ! -f cf.tgz ]; then exit 1; fi
          tar -xzf cf.tgz
          if [ ! -f cf8 ]; then exit 1; fi
          sudo mv cf8 /usr/local/bin/cf
          sudo chmod +x /usr/local/bin/cf
          cf --version

      - name: Install CF Plugin
        run: cf install-plugin -r CF-Community multiapps -f

      - name: Login to SAP BTP
        run: |
          cf login -a ${{ secrets.CF_API }} \
                   -u ${{ secrets.CF_USER }} \
                   -p ${{ secrets.CF_PASSWORD }} \
                   -o ${{ secrets.CF_ORG }} \
                   -s ${{ secrets.CF_SPACE }}

      - name: Deploy to Cloud Foundry
        run: cf deploy gen/mta.tar -f